### PR TITLE
[WIP] Return promise from native module on all calls

### PR DESCRIPTION
**Pull request by esbenvb**
To avoid application crashes when trying to track events or screens, before Segment is initialized, we need to catch these exceptions and let JS handle the errors using a returned promise.

Example:
```js
    Segment.screen(event)
      .then(result => {
        console.log(result) // true
      })
      .catch(error => {
        console.error(error)
      })
```

TODO:

- [ ] Maybe adjust exception levels on Android.

### CODE REVIEW

**Comment by kevinpelgrims** [comment]
I am a fan of failing as quickly as possible, and so I don't agree with the idea of this PR.
As you can now see in the example app, if you don't handle the promises, then it will appear as if everything works fine. Crashing the app ensures that whoever uses this module remembers to initialize Segment before they start using it.
Another issue I have with this PR, is that we're shielding the Segment implementation from whoever uses the module. The native Segment SDK chooses to crash when it's not set up properly, and this module is meant to be a wrapper around the SDK, so we shouldn't alter its behavior.

**Comment by esbenvb** [comment]
I just tried running it without catching the rejected promises, and the native errors from Segment are shown to the developers, so no silent fail, unless the app choose to to that explicitly.

screen shot 2017-12-12 at 11 06 38

I discussed a few options with @kevinpelgrims 

1: Keeping state in JS and check whether segment has been setup before calling. The problem with that is that the segment setup is living in the native code, which means that the JS part will get out of sync if reloading the RN app etc. 

2. Exporting a boolean function to handle the issues in 1), and tell if segment is initialized. The problem is that (at least on iOS) the shared instance itself is a private property of segment, and we call a method that gives us that instance. But we cannot check for being `NIL`, since the method will throw an exception when called if it's `NIL`. Therefore, we'd need to try/catch the exception.

3. Keeping an additional state in the native code which indicates whether segment has been initialized and then check for that value when resolving/rejecting the promises. This will give the developer less detailed error messages, since we don't get the actual error messages from native Segment, as we do now with the try/catch.

**Comment by esbenvb** [comment]
Another important thing to keep in mind is that the target audience for this module are JS developers, which may not have any native expericence. Making it reject a promise, which is then handled and displayed as an error/warning by React Native is far more developer friendly than crashing the app and make the developer go through the native logs for ios/android. And it's still very clear to the developer that something is wrong.

**Comment by esbenvb** [comment]
@kevinpelgrims @romainbriche It would be nice of we could get this one done today, so we'll avoid trouble with the come up with your approval of this or any desired changes.

**Comment by skovhus** [comment]
> I am a fan of failing as quickly as possible, and so I don't agree with the idea of this PR.

Agree. 

> The native Segment SDK chooses to crash when it's not set up properly

Good reason for keeping the crash here.

> Making it reject a promise, which is then handled and displayed as an error/warning by React Native is far more developer friendly than crashing the app and make the developer go through the native logs for ios/android

Most developers like fail early instead. Doesn't get more developer friendly that that.

## Suggestions

If we really need this then provide an API call where you can check if it already has been configured. Similar to `raven-js`.

**Comment by esbenvb** [comment]
@skovhus We need this beause we have disabled the segment setup in DEV mode. This might lead to app crashes when the app is in dev mode, since we still call the track functions that hits the native segment module. 

>> The native Segment SDK chooses to crash when it's not set up properly
> Good reason for keeping the crash here.

It actually throws an exception. Which you can catch and handle in your native app, or let it crash.

If we don't catch this exception and provide it in a promise (like suggested here), we are taking away that choice from the consumers of this module. 

> Most developers like fail early instead. Doesn't get more developer friendly that that.

I guess most RN developers prefers an RN-based warning/error instead of looking in crash logs? Is it common behavior of other RN wapper modules to crash the entire app on errors?

> If we really need this then provide an API call where you can check if it already has been configured. 

This information is not directly accessible in the iOS code. We just get an exception when asking for the shared instance of segment, if it's not configured.

**Comment by skovhus** [comment]
Which other cases would the tracking library throw exceptions? Are there other cases like HTTP call failed where this will also crash the app?

**Comment by skovhus** [comment]
> 1. Keeping state in JS and check whether segment has been setup before calling. The problem with that is that the segment setup is living in the native code, which means that the JS part will get out of sync if reloading the RN app etc.

Will it really get out of sync? The JS environment is just suspended so I imagine that this actually would work fine. But let us investigate.

**Comment by esbenvb** [comment]
> Will it really get out of sync? The JS environment is just suspended so I imagine that this actually would work fine. But let us investigate.

I have experienced it being still configured after inserting the `return` statement to disable configuration, and reloading the RN app.

**Comment by esbenvb** [comment]
> Which other cases would the tracking library throw exceptions? Are there other cases like HTTP call failed where this will also crash the app?

I guess that's hard to tell without going through the code in these pods:
https://github.com/leoilab/imagine-rn/blob/development/ios/Podfile - but I really hope that none of the modules throws exceptions when being used properly :)

**Comment by kevinpelgrims** [comment]
> Which other cases would the tracking library throw exceptions? Are there other cases like HTTP call failed where this will also crash the app?

Simple (and likely incomplete) check is to search for `throw` in this class: https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/Analytics.java

I can tell you with certainty that HTTP errors are caught, though:
1. https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/Client.java#L112
2. https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/Analytics.java#L369

**Comment by kevinpelgrims** [comment]
On a slightly related note, it would probably make sense to catch these before we call any native code: https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/Analytics.java#L600

**Comment by skovhus** [comment]
So from what I can see, all exceptions thrown are severe error that the user should see.

Swallowing these errors in a promise and making it up to the user to dig them out is not a good solution to me. Leaves to much responsibility to the user and isn't user friendly.

But I see that crashing the app is not that user friendly either. : )

In case of native code throwing an error, we might call `console.error` or rethrow the error from index.js instead. That would give some more user friendly errors.

**Comment by esbenvb** [comment]
> In case of native code throwing an error, we might call `console.error` or rethrow the error from index.js instead. That would give some more user friendly errors.

As shown, the developer will get the yellow screen with the error message, if he doesn't catch the rejected promise from the module. To make it even more clear that something is wrong, we talked about making this a red error screen instead, by catching it in the module JS code if it's not caught by the app, and calling `console.error`. What do you think about that?

**Comment by skovhus** [comment]
> What do you think about that?

Seems very close to what I suggested. But I'm not convinced we should expose the promise to the user though.

**Comment by esbenvb** [comment]
> But I'm not convinced we should expose the promise to the user though.

What other approaches than promises do you normally use in RN, when calling an operation that might fail in certain circumstances?

**Comment by kevinpelgrims** [comment]
I agree that crashing is not the perfect solution and passing some kind of error would make more sense here. In that case, I think `throw new Error()` is the way to go. This wouldn't solve the problem that @esbenvb described, but really I think that's a flaw in the implementation, rather than the library. The outcome of `throw new Error()` will effectively be the same (the app will stop functioning), but a bit more obvious to the developer that is using the module.

**Comment by esbenvb** [comment]
Yes, I also like that solution as an alternative to returning a promise on every call.

But I think the bridge betweeen JS and native still needs to use the promises, so the changes should be in `index.js` which should catch the promise and throw the exception based on the rejection of the bridge promise. Right?

**Comment by skovhus** [comment]
As discussed offline I think this doesn't have any high priority for us right now.

I suggest closing this PR and creating a ticket listing the problem (and a few different ideas and solutions). Other contributors might have ideas or suggestions.

**Comment by romainbriche** [comment]
I agree with @skovhus

**Comment by esbenvb** [comment]
Fine I'll make a ticket

**Pull request closed without merging**
