### PR TITLE
Add intercom support

### PR DESCRIPTION
**Pull request by luisfmsouza**
Add Intercom [iOS](https://github.com/segment-integrations/analytics-ios-integration-intercom) and [Android](https://github.com/segment-integrations/analytics-android-integration-intercom) support.

Reference: #33

### CODE REVIEW

**Comment by kevinpelgrims** [comment]
Thanks for the PR!
Have you tried building the Android module? It will not build, because the Intercom library is not referenced. You should add a line to the `build.gradle` file similar to these:
https://github.com/leoilab/react-native-analytics-segment-io/blob/df2dd2492a1acec93eeafea4be51fbaf33ce3740/android/build.gradle#L39-L54

**Comment by luisfmsouza** [comment]
Thanks for your friendly reminder @kevinpelgrims.

I've included Intercom reference on `build.gradle`.

**Comment by localredhead** [comment]
Hello, I am having some issues configuring this new functionality with android -
 I wonder if more configuration steps are needed? https://github.com/leoilab/react-native-analytics-segment-io/issues/42

**Comment by romainbriche** [comment]
@localredhead it doesn't seem that the issue you are referring to is caused by a lack of configuration

**Pull request merged**
