### PR TITLE
iOS: xcodebuild build fix

### PR DESCRIPTION
**Pull request by romainbriche**
When running `react-native run-ios` from a cleaned project the build fails as it cannot find `#import "Analytics/SEGAnalytics.h"`.

This PR addresses this issue.

### CODE REVIEW

**Comment by romainbriche** [comment]
To easily test if it works you can run the following command: 
```
git clone git@github.com:leoilab/react-native-analytics-segment-io.git && cd react-native-analytics-segment-io && git checkout xcodebuild-fix && cd example && npm install && cd ios && pod install && cd .. &&  react-native run-ios
```

**Comment by kevinpelgrims** [comment]
🎉

**Comment by casperstorm** [comment]
Worked just fine, thanks @romainbriche.

**Comment by skovhus** [comment]
I tied using 3.0.1. But using the RN CLI I still need to built the project twice. First time I get a build failure with a missing segment header file.

**Comment by GioLogist** [comment]
I'm still receiving this error myself (without use_frameworks)

**Comment by romainbriche** [comment]
@GioLogist which version of Cocoapods are you using?

**Comment by GioLogist** [comment]
@romainbriche 1.3.1

**Pull request merged**
